#---------------------------
# Hexo Theme Miracle
# Author: HiFun Team
# GitHub: https://github.com/hifun-team/hexo-theme-miracle
#---------------------------

#---------------------------
# å…¨å±€
# Global
#---------------------------

global:

    # ç”¨äºæµè§ˆå™¨æ ‡ç­¾çš„å›¾æ ‡
    # Icon for browser tab
    favicon: https://cdn.staticaly.com/gh/JesseJeson/picture-api@master/20220812/ico.2ayx6svgfi3o.png

    # ç”¨äºè‹¹æœè®¾å¤‡çš„å›¾æ ‡
    # Icon for Apple touch
    apple_touch_icon: https://cdn.staticaly.com/gh/JesseJeson/picture-api@master/20220812/ico.2ayx6svgfi3o.png

    # å¼ºåˆ¶æ‰€æœ‰é“¾æ¥å‡çº§ä¸º HTTPSï¼ˆé€‚ç”¨äºå›¾ç‰‡ç­‰èµ„æºå‡ºç° HTTP æ··å…¥æŠ¥é”™ï¼‰
    # Force all links to be HTTPS (applicable to HTTP mixed error)
    force_https: true

    # å¯¼èˆªæ å·¦ä¾§çš„æ ‡é¢˜ï¼Œä¸ºç©ºåˆ™æŒ‰ hexo config ä¸­ `title` æ˜¾ç¤º
    # The title on the left side of the navigation bar. If empty, it is based on `title` in hexo config
    nav_title: "Histcat's Blog"

    # æµè§ˆå™¨æ ‡ç­¾é¡µä¸­çš„æ ‡é¢˜åˆ†éš”ç¬¦ï¼Œæ•ˆæœï¼š æ–‡ç« å - ç«™ç‚¹å
    # Title separator in browser tab, eg: article - site
    title_join_string: " - "

    # ä¸»é¢˜å­—ä½“è®¾ç½®
    # Theme font settings
    font:
        family: # "'Noto Sans SC', sans-serif"
        css: # https://fonts.googleapis.com/css2?family=Noto+Sans+SC&display=swap

    # æ¯æ¬¡ç”Ÿæˆé¡µé¢åï¼Œæ£€æµ‹ä¸»é¢˜æ˜¯å¦ä¸ºæœ€æ–°ç‰ˆæœ¬
    # Every time the page is generated, detect whether the theme is the latest version
    version_check: true

    # ç½‘é¡µè®¿é—®ç»Ÿè®¡
    # Analysis of website visitors
    web_analytics:
        # ç™¾åº¦ç»Ÿè®¡çš„ Keyï¼Œå€¼éœ€è¦è·å–ä¸‹æ–¹é“¾æ¥ä¸­ `hm.js?` åè¾¹çš„å­—ç¬¦ä¸²
        # Baidu analytics, get the string behind `hm.js?`
        # See: https://tongji.baidu.com/sc-web/10000033910/home/site/getjs?siteId=13751376
        baidu:
        
        # Google ç»Ÿè®¡çš„ Tracking ID
        # Google analytics, set Tracking ID
        # See: https://developers.google.com/analytics/devguides/collection/analyticsjs
        google:
        
        # 51.la ç«™ç‚¹ç»Ÿè®¡ ID
        # 51.la analytics
        # See: https://www.51.la/user/site/index
        woyaola: 

        # å‹ç›Ÿ/cnzz ç«™ç‚¹ç»Ÿè®¡ web_id
        # cnzz analytics
        # See: https://web.umeng.com/main.php?c=site&a=show
        cnzz:

        busuanzi:
            enable: false
            # é¡µé¢æ˜¾ç¤ºçš„æ–‡æœ¬ï¼Œ{} æ˜¯æ•°å­—çš„å ä½ç¬¦ï¼ˆå¿…é¡»åŒ…å«)ï¼Œä¸‹åŒ
            # Displayed text, {} is a placeholder for numbers (must be included), the same below.
            pv_format: "æ€»è®¿é—®é‡ {} æ¬¡"
            uv_format: "æ€»è®¿å®¢æ•° {} äºº"

    # åœ¨é¡µé¢åº•éƒ¨åŠ å…¥ Copyright
    # Copyright
    copyright:
        enable: true
        # å¼€å§‹å¹´ä»½ï¼Œä¸å¡«ä¸æ˜¾ç¤º
        # Start year, no display if not filled.
        from_year: 2020
        # ç»“æŸå¹´ä»½
        # End year.
        to_year: 2023
        name: "Histcat's Blog"

    # å“€æ‚¼æ¨¡å¼ï¼Œç½‘é¡µé»‘ç™½
    # Mourning mode, web page black and white
    memorial:
        enable: false
        # æ—¥æœŸ, (M-D)
        # Date, (M-D)
        # eg: 7-8, 9-30, 12-1, 12-30 ...
        date: 
            - "7-8"
            - "12-13"

# æœç´¢
# Search
search:
    enable: true
    # æœç´¢ç´¢å¼•æ–‡ä»¶çš„è·¯å¾„ï¼Œå¯ä»¥æ˜¯ç›¸å¯¹è·¯å¾„æˆ–å¤–ç«™çš„ç»å¯¹è·¯å¾„
    # Path for search index file, it can be a relative path or an absolute path.
    path: /search.json

    # æœç´¢çš„èŒƒå›´
    # Search field
    # Options: post | page | all
    field: post

# ä¸­å›½å¤§é™†å¤‡æ¡ˆ
# For Chinese mainland website policy, other areas keep disable.
beian:
    enable: false
    # ICP è¯å·
    icp_text: äº¬ICPè¯ 123456 å·
    # å…¬å®‰å¤‡æ¡ˆå·ï¼Œä¸å¡«åˆ™åªæ˜¾ç¤º ICP
    police_text: äº¬å…¬ç½‘å®‰å¤‡ 12345678 å·
    # å…¬å®‰å¤‡æ¡ˆçš„ç¼–å·ï¼Œç”¨äºé“¾æ¥è·³è½¬æŸ¥è¯¢
    police_code: 12345678
    # å…¬å®‰å¤‡æ¡ˆçš„å›¾ç‰‡. ä¸ºç©ºæ—¶ä¸æ˜¾ç¤ºå¤‡æ¡ˆå›¾ç‰‡
    police_icon: /img/police_beian.png

# è‡ªå®šä¹‰
# Custom
custom:
    # é¡µé¢å¤´éƒ¨ HTML
    # Page header HTML
    header_html: '<link rel="stylesheet" href="https://jsd.onmicrosoft.cn/npm/katex@0.16.4/dist/katex.min.css" integrity="sha384-vKruj+a13U8yHIkAyGgK1J3ArTLzrFGBbBc0tDp4ad/EyewESeXE/Iv67Aj8gKZ0" crossorigin="anonymous">
    <script defer src="https://jsd.onmicrosoft.cn/npm/katex@0.16.4/dist/katex.min.js" integrity="sha384-PwRUT/YqbnEjkZO0zZxNqcxACrXe+j766U2amXcgMg5457rve2Y7I6ZJSm2A0mS4" crossorigin="anonymous"></script>'
    # é¡µé¢åº•éƒ¨ HTML
    # Page footer HTML
    footer_html: '<p>æ€»è®¿é—®é‡ <span id="busuanzi_value_site_pv"></span> æ¬¡ æ€»è®¿å®¢æ•° <span id="busuanzi_value_site_uv"></span> äºº</p>'    # é¡µé¢è‡ªå®šä¹‰ JSï¼ˆåº•éƒ¨å¼•å…¥ï¼‰
    # Page custom JS (introduced at the bottom)
    js: https://npm.elemecdn.com/penndu@1.0.0/bsz.js
    # é¡µé¢è‡ªå®šä¹‰ CSS
    # Page custom CSS
    css: https://blog.histcat.top/self-css.css

##---------------------------
## ä¸»é¢˜
## Theme
##---------------------------
#theme:
#    # æ·±è‰²æ¨¡å¼
#    # Dark mode
#    # é»˜è®¤å¼€å¯ã€‚


#---------------------------
# ä¸»é¡µ
# Homepage
#---------------------------
index:
    # åç§°
    # Name
    name: "Histcat's Blog"
    # Slogan
    slogan: ä¸€åªoierçš„å°çª

    # æ–‡ç« é€šè¿‡ `sticky` æ’åº
    # The posts are sorted by `sticky`
    post_sticky:
        enable: true
        text: "[TOP]"

    # æ–‡ç« å¡ç‰‡æ˜¯å¦æ˜¾ç¤ºç›¸å…³ä¿¡æ¯ï¼ˆæ—¶é—´ã€åˆ†ç±»ã€æ ‡ç­¾ï¼‰
    # Whether the article card displays relevant information (time, category, label)
    post_meta:
        date: true
        category: true
        tag: true

    # è‡ªåŠ¨æˆªå–æ–‡ç« æ‘˜è¦ï¼Œå‰ 200 å­—ç¬¦
    # Auto extract post, First 200 characters.
    auto_excerpt:
        enable: true

navbar:
    # å¯¼èˆªæ èœå•ï¼Œå¯è‡ªè¡Œå¢å‡.
    # Navigation bar menu.
    menu:
        é¦–é¡µ: /
        å½’æ¡£: /archives/
        åˆ†ç±»: /categories/
        æ ‡ç­¾: /tags/
        è¯´è¯´: /talk/
        å‹é“¾: /links/
        å…³äº: /about/
        ğŸš‡å¼€å¾€: https://www.travellings.cn
        # ...


#---------------------------
# æ–‡ç« é¡µ
# Post Page
#---------------------------
post:
    # æ–‡ç« å…ƒä¿¡æ¯
    # Post meta
    meta:
        # ä½œè€…ï¼Œä¼˜å…ˆæ ¹æ® `front-matter` é‡Œ `author` å­—æ®µï¼Œå…¶æ¬¡æ˜¯ `hexo` é…ç½®ä¸­ `author` å€¼
        # Author, based on `author` field in front-matter, if not set, based on `author` value in hexo config
        author: true

        # æ–‡ç« æ—¥æœŸï¼Œä¼˜å…ˆæ ¹æ® `front-matter` é‡Œ date å­—æ®µï¼Œå…¶æ¬¡æ˜¯ .md æ–‡ä»¶æ—¥æœŸ
        # Post date, based on `date` field in front-matter, if not set, based on create date of .md file
        date: true

        # æ ¼å¼å‚ç…§ ISO-8601 æ—¥æœŸæ ¼å¼åŒ–
        # ISO-8601 date format
        # See: http://momentjs.cn/docs/#/parsing/string-format/
        date_format: "YYYY-MM-DD"
    
    # å­—æ•°ç»Ÿè®¡
    # Word count
    wordcount:
        enable: true

        # æ‰€æ˜¾ç¤ºçš„æ–‡æœ¬ï¼Œ{} æ˜¯æ•°å­—çš„å ä½ç¬¦ï¼ˆå¿…é¡»åŒ…å«ï¼‰
        # Displayed text, {} is a placeholder for numbers (must be included)
        format: "å…± {} å­—"

    # ä¼°è®¡é˜…è¯»å…¨æ–‡éœ€è¦çš„æ—¶é•¿
    # Estimate the time required to read the full text
    min2read:
        enable: false
        format: "é¢„è®¡ {} åˆ†é’Ÿ"
        # æ¯åˆ†é’Ÿé˜…è¯»å¤šå°‘å­—ï¼Œå¦‚æœæ˜¯æŠ€æœ¯æ–‡ç« ï¼Œå»ºè®®é™ä½
        # Words read per minute
        words: 120

    # æ–‡ç« é˜…è¯»é‡ç»Ÿè®¡
    # Article reading statistics
    # ç”± ä¸è’œå­ æä¾›æ”¯æŒ
    # Supported by busuanzi
    views:
        enable: false
        format: "å…± {} æ¬¡é˜…è¯»"

    # è¯„è®ºæ’ä»¶
    # Comment plugin
    comment: true

    # ä»£ç æ˜¾ç¤ºè®¾ç½®
    # Code display setting
    code:
        # ä»£ç é«˜äº®
        # Code highlight
        highlight: true
    
    # æ–‡ç« ç›®å½•
    # Article Directory
    toc:
        enable: true
        type: hexo
        hexo:
            # æ˜¾ç¤ºç¼–å·
            # Displays list number
            list_number: true
            # ç”Ÿæˆ TOC çš„æœ€å¤§æ·±åº¦
            # Maximum heading depth of generated toc
            max_depth: 
            # ç”Ÿæˆ TOC çš„æœ€å°æ·±åº¦
            # Minimum heading depth of generated toc
            min_depth: 

    # è„šæ³¨
    # Footnote
    footnote:
        enable: true
        # è¾“å‡ºåœ¨è„šæ³¨åˆ—è¡¨å‰çš„æ–‡å­—ï¼ˆæ”¯æŒ HTMLï¼‰
        # The text before the footnote list (supports HTML)
        header: ''
    
    # å›¾ç‰‡ç¯ç®±
    # Picture Fancybox
    fancybox:
        enable: true
    
    mermaid:
        enable: true
        # å¼€å¯åï¼Œåªæœ‰åœ¨æ–‡ç«  Front-matter é‡ŒæŒ‡å®š `mermaid: true` æ‰ä¼šåœ¨æ–‡ç« é¡µå¯åŠ¨å…¬å¼è½¬æ¢ï¼Œä»¥ä¾¿åœ¨é¡µé¢ä¸åŒ…å«å…¬å¼æ—¶æé«˜åŠ è½½é€Ÿåº¦
        # If true, only set `mermaid: true` in Front-matter will enable mermaid, to load faster when the page does not contain mermaid
        specific: true

        # See: http://mermaid-js.github.io/mermaid/
        options: { theme: 'default' }

    # ç‰ˆæƒå£°æ˜ï¼Œä¼šæ˜¾ç¤ºåœ¨æ¯ç¯‡æ–‡ç« çš„ç»“å°¾
    # Copyright, will be displayed at the end of each post
    copyright:
        enable: true
        authorURL: /
        content: 'æœ¬åšå®¢æ‰€æœ‰æ–‡ç« é™¤ç‰¹åˆ«å£°æ˜å¤–ï¼Œå‡é‡‡ç”¨ <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh" rel="nofollow noopener">CC BY-SA 4.0 åè®®</a> ï¼Œè½¬è½½è¯·æ³¨æ˜å‡ºå¤„ï¼Œè°¢è°¢ã€‚'
        # CC ç‰ˆæƒåè®®ï¼Œæ˜¾ç¤º CC ç‰ˆæƒçš„ SVG
        cc: true
        # å¤åˆ¶å†…å®¹æ—¶è¿½åŠ ç‰ˆæƒ
        clipboard: 
            enable: false
            content: ''

    # æ–‡æœ«æ‰“èµ
    # Donate
    donate:
        enable: false
        # æ‰“èµæ–‡å­—
        text: "å–œæ¬¢è¿™ç¯‡æ–‡ç« ï¼Ÿä¸ºä»€ä¹ˆä¸è€ƒè™‘æ‰“èµä¸€ä¸‹ä½œè€…å‘¢ï¼Ÿ"
        # æ–¹å¼
        # Way
        way:
            # èµèµ: https://yfun.top/?ref=donate
            # ...


    # é˜…è¯»è¿›åº¦
    readingProgress:
        enable: false





#---------------------------
# è¯„è®ºæ’ä»¶
# Comment plugins
#
# å¼€å¯è¯„è®ºéœ€è¦å…ˆè®¾ç½®ä¸Šæ–¹ `post: comment: true`ï¼Œç„¶åæ ¹æ® `type` è®¾ç½®ä¸‹æ–¹å¯¹åº”çš„è¯„è®ºæ’ä»¶å‚æ•°
# Enable comments need to be set `post: comments: enable: true`, then set the corresponding comment plugin parameters below according to `type`
#---------------------------
comment:

    # æŒ‡å®šçš„æ’ä»¶ï¼Œéœ€è¦åŒæ—¶è®¾ç½®å¯¹åº”æ’ä»¶çš„å¿…è¦å‚æ•°
    # The specified plugin needs to set the necessary parameters at the same time
    # Options: gitalk | valine | waline | twikoo | giscus | detalk | artalk
    type: twikoo

    # Gitalk
    # See: https://github.com/gitalk/gitalk#options
    gitalk:
        clientID: 
        clientSecret: 
        repo: 
        owner: 
        admin: ['name']
        language: zh-CN
        labels: ['Gitalk']
        perPage: 10
        pagerDirection: last
        distractionFreeMode: false
        createIssueManually: true

    # Valine
    # See: https://valine.js.org/configuration.html
    # Valine å­˜åœ¨ç”¨æˆ·éšç§æ³„éœ²é—®é¢˜ï¼Œå¯èƒ½ä¼šæ³„éœ²ç”¨æˆ·çš„éšç§ä¿¡æ¯ï¼ˆIP ç­‰ï¼‰ï¼Œä¸å†å»ºè®®ä½¿ç”¨ã€‚
    valine:
        appid: 
        appkey: 
        placeholder:
        path: window.location.pathname
        avatar: mp
        meta: ['nick','mail','link']
        pageSize: 10
        lang: zh-CN
        highlight: true
        avatarForce: false
        recordIP: false
        serverURLs: 
        enableQQ: false
        requiredFields: ['nick','mail']

    # Waline
    # See: https://waline.js.org/client/basic.html
    waline:
        serverURL:
        placeholder:
        path: window.location.pathname
        avatar: mp
        meta: ['nick','mail','link']
        pageSize: 10
        highlight: true
        avatarCDN:
        avatarForce: false
        requiredMeta: ['nick','mail']
        login: enable

    # Twikoo
    # See: https://twikoo.js.org/quick-start.html#%E5%89%8D%E7%AB%AF%E9%83%A8%E7%BD%B2
    twikoo:
        envid: https://twikoo.histcat.top
        region: ap-shanghai
        path: window.location.pathname
        # æ˜¯å¦ä¸º Vercel ç‰ˆæœ¬
        # è¿™æ˜¯ä¸»é¢˜è®¾ç½®ï¼Œæ˜¯ Vercel è¯·å¡«å†™ true
        # Vercel ç‰ˆæœ¬ä¸ä¼šå¼•å…¥å¸¦æœ‰è…¾è®¯ SDK çš„ all.min.js
        isVercel: true

    # giscus
    # See: https://giscus.app/
    giscus: 
        repo: 
        repoID: 
        category: 
        categoryID: 
        mapping: 
        term: 
        strict: 
        reactionsEnabled: 
        emitMetadata: 
        inputPosition: 
        theme: 
        lang: 
        loading: 

    # Detalk.js
    # https://detalk.js.org/
    # Free, Simple and Powerful Comment Plugin.
    detalk:
        config:
            # Backend URL
            url: ''
            # ä¸è¦ä¿®æ”¹æ­¤é¡¹
            # DO NOT edit this config.
            el: '#detalk'
            # Label
            label:
                admin:
                    name: åšä¸»
                    class: label-green
            # reCAPTCHA
            recaptchaSiteKey: 
            login:
                github:
            owo: 

    artalk:
        # å¡«ä½ artalkåç«¯çš„åŸŸå
        envid: ''


#---------------------------
# åˆ†ç±»é¡µ
# Category Page
#---------------------------
category:
    enable: true


#---------------------------
# å½’æ¡£é¡µ
# Archive Page
#---------------------------
archive:
    title: å½’æ¡£

#---------------------------
# æ ‡ç­¾é¡µ
# Tag Page
#---------------------------
tag:
    enable: true
    subtitle:
    tagcloud:
        min_font: 15
        max_font: 30
        unit: px
        start_color: "#acb3c2"
        end_color: "#454d5d"

#---------------------------
# å‹é“¾é¡µ
# Links Page
#---------------------------
links:
    enable: true
    items:
        
    # JSON å‹é“¾
    # JSON Links
    json_links:
        enable: true

        # JSON æ–‡ä»¶é“¾æ¥
        # Link to JSON file
        item_links: https://s.cky.qystu.cc/gh/histcat/friends@main/friends.json

#---------------------------
# è¯´è¯´é¡µ
# Talk Page
#---------------------------
talk:
    enable: true

    # Page Title
    title: è¯´è¯´

    # HexoPlusPlus / Artitalk / Detalk
    # Options: HPP | Artitalk | Detalk
    type: HPP

    # HexoPlusPlus, See: https://hexoplusplus.js.org/use/hexoinit.html
    HPP:
        domain: hpp-admin.histcat.top
        limit: 10
        start: 0

    # Artitalk, See: https://artitalk.js.org/settings.html
    Artitalk:
        appId: KRERflTJWOjyOSKYVdJ7zoQk-MdYXbMMI
        appKey: Ki2BfqwzH43Oxr4bnFAOwo2L
        serverURL: https://shuoshuo.histmoe.eu.org
        lang: zh
        pageSize: 6
        shuoPla: éšä¾¿è¯´è¯´...
        avatarPla: 
        motion: 1
        bgImg:


    Detalk:
        config:
            # Backend URL
            url: ''
            # ä¸è¦ä¿®æ”¹æ­¤é¡¹
            # DO NOT edit this config.
            el: '#detalk'
            # Label
            label:
                admin:
                    name: åšä¸»
                    class: label-green
            # reCAPTCHA
            recaptchaSiteKey: 
            login:
                github: 
            owo: 

# HexoPlusPlus ç­¾åˆ°
hpp_time:
    enable: false
    domain:


#---------------------------
# 404é¡µ
# 404 Page
#---------------------------
page404:
    enable: true


#---------------------------
# ä»¥ä¸‹æ˜¯é…ç½® JS CSS é™æ€èµ„æºçš„ URL å‰ç¼€ï¼Œå¯ä»¥è‡ªå®šä¹‰æˆ CDN åœ°å€ï¼Œ
# å¦‚æœéœ€è¦ä¿®æ”¹ï¼Œæœ€å¥½ä½¿ç”¨ä¸é»˜è®¤é…ç½®ç›¸åŒçš„ç‰ˆæœ¬ï¼Œä»¥é¿å…æ½œåœ¨çš„é—®é¢˜ï¼Œ
# åœ¨ç«™ç‚¹ä¸Šå¯ç”¨ HTTPS æ—¶ï¼Œè¯·ä½¿ç”¨ CDN åœ°å€çš„ HTTPS åè®®ï¼Œ
# ** å¦‚æœä½ ä¸çŸ¥é“å¦‚ä½•è®¾ç½®ï¼Œè¯·ä¸è¦åšä»»ä½•æ”¹åŠ¨ **
#
# Here is the url prefix to configure JS and CSS static assets. Set CDN addresses you want to customize.
# Be aware that you would better use the same version as default ones to avoid potential problems.
# Use the HTTPS protocol of CDN url when you enable HTTPS on your site.
# DO NOT EDIT THE FOLLOWING SETTINGS UNLESS YOU KNOW WHAT YOU ARE DOING
#---------------------------

static_prefix:
    busuanzi: //busuanzi.ibruce.info/busuanzi/2.3/
    gitalk: https://cdn.jsdelivr.net/npm/gitalk@1/dist/
    valine: https://cdn.jsdelivr.net/npm/valine@1.4.14/dist/
    waline: https://cdn.jsdelivr.net/npm/@waline/client/dist/
    fancybox: https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.5.7/dist/
    mermaid: https://cdn.jsdelivr.net/npm/mermaid@8.8.3/dist/ 
    twikoo: https://cdn.staticfile.org/twikoo/1.6.16/
    artitalk: https://unpkg.com/artitalk@3.3.4/artitalk.js
    hpp: https://js.histcat.top/gh/HexoPlusPlus/HexoPlusPlus@1.2.0/
    detalk: https://cdn.jsdelivr.net/npm/@detalk/static@1.3.1/dist/
    artalk: https://cdn.jsdelivr.net/npm/artalk@2.4.4/dist/